set_property PACKAGE_PIN K19 [get_ports clk];                  set_property IOSTANDARD LVCMOS33 [get_ports clk];  set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk}]
set_property PACKAGE_PIN T18 [get_ports reset_n];              set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property PACKAGE_PIN U21 [get_ports entree];               set_property IOSTANDARD LVCMOS33 [get_ports entree]
set_property PACKAGE_PIN V20 [get_ports restart];              set_property IOSTANDARD LVCMOS33 [get_ports restart]
set_property PACKAGE_PIN V22 [get_ports sortie[0]];            set_property IOSTANDARD LVCMOS33 [get_ports sortie[0]]
set_property PACKAGE_PIN W22 [get_ports sortie[1]];            set_property IOSTANDARD LVCMOS33 [get_ports sortie[1]]
set_property PACKAGE_PIN W21 [get_ports sortie[2]];            set_property IOSTANDARD LVCMOS33 [get_ports sortie[2]]
set_property PACKAGE_PIN Y22 [get_ports sortie[3]];            set_property IOSTANDARD LVCMOS33 [get_ports sortie[3]]
set_property PACKAGE_PIN Y21 [get_ports sortie[4]];            set_property IOSTANDARD LVCMOS33 [get_ports sortie[4]]
set_property PACKAGE_PIN AB22 [get_ports sortie[5]];           set_property IOSTANDARD LVCMOS33 [get_ports sortie[5]]
set_property PACKAGE_PIN AA21 [get_ports sortie[6]];           set_property IOSTANDARD LVCMOS33 [get_ports sortie[6]]
set_property PACKAGE_PIN AA20 [get_ports aff_ebl];             set_property IOSTANDARD LVCMOS33 [get_ports aff_ebl]
